### PR TITLE
Created Plan entity

### PR DESCRIPTION
**Pull request by eSuminski**
I implemented the Comparable interface, let me know if we are not doing that and I will change it.

### CODE REVIEW

**Review by AMINESFAHANI — CHANGES_REQUESTED** [review]
why we need the compare to method by id?

**Comment by eSuminski** [comment]
Short answer: it allows for easy sorting: you can simply call Collections.sort() on any list that has Plan objects in it and the list will sort the plans by their IDs. You don't HAVE to have it, but the benefit of using it is we don't have to create our own code to order collections of our entitites. 

a more detailed explanation: https://www.javatpoint.com/Comparable-interface-in-collection-framework

**Review by eSuminski — COMMENTED** [review]
Thank you!

**Review by AMINESFAHANI — APPROVED** [review]
looks good

**Pull request merged**
